spring:
  datasource:
    url: jdbc:mysql://192.168.0.102:3306/chat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.cheng.chatroom.entity
